[build]
  # Build command for Vite
  command = "npm run build"
  # Output directory where Vite builds to
  publish = "dist"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variable configuration
# Note: Actual values should be set in Netlify Dashboard > Site Settings > Environment Variables
# This section documents the required variables
[build.environment]
  # Node version
  NODE_VERSION = "18"

# Headers for better security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/commodities/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
